/* Removed legacy EnftAccount import (no longer generated by program) */
import { ellipsify, UiWalletAccount } from '@wallet-ui/react'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { AppExplorerLink } from '@/components/app-explorer-link'
/* Removed legacy close button */
/* Removed legacy decrement button */
/* Removed legacy increment button */
/* Removed legacy set button */

export function EnftUiCard({ account }: { account: UiWalletAccount }) {
  return (
    <Card>
      <CardHeader>
        <CardTitle>Staking Overview</CardTitle>
        <CardDescription>
          Account: <AppExplorerLink address={account.address} label={ellipsify(account.address)} />
        </CardDescription>
      </CardHeader>
      <CardContent>
        <div className="flex gap-4 justify-evenly">
          {/* removed legacy increment button */}
          {/* removed legacy set button */}
          {/* removed legacy decrement button */}
          {/* removed legacy close button */}
        </div>
      </CardContent>
    </Card>
  )
}
